# Generated by Django 5.2.5 on 2025-10-04 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_organizer_remove_ticket_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendee',
            field=models.ManyToManyField(blank=True, related_name='attended_events', through='api.Ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
