# Generated by Django 5.2.6 on 2025-10-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeuser',
            name='ticket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendee',
        ),
        migrations.AddField(
            model_name='event',
            name='attendee',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
