# Generated by Django 5.2.6 on 2025-10-05 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_attendeeuser_ticket_remove_event_attendee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='attendee_user',
            new_name='attendee',
        ),
        migrations.RemoveField(
            model_name='attendeeuser',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_title',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_title',
            field=models.CharField(default='Untitled Event', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.CharField(default='TBA', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_email',
            field=models.EmailField(default='no-email@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='api.event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.CharField(default='LEGACY-TICKET', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
