# Generated by Django 5.2.7 on 2025-10-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_attendee_user_ticket_attendee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_category',
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date_register',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date_register',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
