# Generated by Django 5.2.7 on 2025-10-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_event_event_category_event_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
