# Generated by Django 5.2.7 on 2025-10-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ticket_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_create_date']},
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
