# Generated by Django 5.2.7 on 2025-10-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_options_event_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
