# Generated by Django 5.2.7 on 2025-10-23 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_options_event_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='event',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_id',
            field=models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='event_id',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.event'),
        ),
        migrations.AddField(
            model_name='rating',
            name='event_id',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.event'),
        ),
        migrations.AddField(
            model_name='rating',
            name='reviewer_id',
            field=models.ForeignKey(blank=True, db_column='reviewer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='liked_datetime',
            field=models.DateTimeField(auto_now_add=True, db_column='liked_datetime'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='api_comment',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='api_rating',
        ),
    ]
