# Generated by Django 5.2.7 on 2025-10-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ticket_approval_status_ticket_checked_in_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeuser',
            name='about_me',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
