# Generated by Django 5.2.7 on 2025-10-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_attendeeuser_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
