# Generated by Django 5.2.6 on 2025-10-29 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_comment_author_remove_comment_event_and_more'),
        ('api', '0012_alter_ticket_approval_status'),
    ]

    operations = [
    ]
