# Generated by Django 5.2.6 on 2025-11-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20251030_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='checked_in_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
