# Generated by Django 5.2.6 on 2025-11-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ticket_checked_in_dates'),
        ('api', '0015_remove_notification_event_and_more'),
    ]

    operations = [
    ]
