# Generated by Django 5.2.8 on 2025-11-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_ticket_approved_at_ticket_rejected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('registration', 'Registration Confirmation'), ('approval', 'Ticket Approved'), ('rejection', 'Ticket Rejected'), ('reminder_24h', '24 Hour Reminder'), ('reminder_1h', '1 Hour Reminder'), ('event_reminder', 'Event Reminder'), ('event_update', 'Event Update'), ('check_in', 'Check-in Confirmation'), ('event_pending_approval', 'Event Pending Approval'), ('event_approved', 'Event Approved'), ('event_rejected', 'Event Rejected')], max_length=50),
        ),
    ]
