# Generated by Django 5.2.8 on 2025-11-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_ticket_approved_at_ticket_rejected_at_and_more'),
        ('api', '0018_eventfeedback'),
    ]

    operations = [
    ]
