# Generated by Django 5.2.8 on 2025-11-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_spots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='schedule',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
