# Generated by Django 5.2.8 on 2025-11-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20251118_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfeedback',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
