# Generated by Django 5.2.6 on 2025-11-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_event_available_spots_alter_event_schedule'),
        ('api', '0020_eventfeedback_anonymous'),
    ]

    operations = [
    ]
