export const CATEGORIES = [
  "Agriculture",
  "Agro-Industry",
  "Architecture",
  "Business Administration",
  "Economics",
  "Education",
  "Engineering",
  "Environment",
  "Fisheries",
  "Forestry",
  "Humanities",
  "Medicine",
  "Nursing",
  "Pharmaceutical Sciences",
  "Science",
  "Social Sciences",
  "Veterinary Medicine",
  "Veterinary Technology",
  "Interdisciplinary Management and Technology",
];
